title: Cthulhu Fthagn!
author: Cthulhu
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
This Description is so aaaawsome it will make the world a better place...

# social links
twitter_username: i-dont-have-twitter
github_username:  FabianEigel

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
